/**
 * Express router paths go here.
 */

export default {
	Base: "/api",
	Users: {
		Base: "/users",
		GetAll: "/all",
		Login: "/login",
		Create: "/create",
		Get: "/me",
		Update: "/me/update",
		Delete: "/me/delete",
	},
	Pets: {
		Base: "/pets",
		GetAll: "/all",
		Create: "/create",
		Get: "/:petId",
		Update: "/:petId/update",
		Delete: "/:petId/delete",
	},
	Stores: {
		PetStores: {
			Base: "/:storeId/petStores",
			Create: "/create",
			Get: "/:petStoreId",
			Update: "/:petStoreId/update",
			Delete: "/:petStoreId/delete",
		},
		VetStores: {
			Base: "/:storeId/vetStores",
			Create: "/create",
			Get: "/:vetStoreId",
			Update: "/:vetStoreId/update",
			Delete: "/:vetStoreId/delete",
		},
		Base: "/stores",
		GetAll: "/all",
		GetAllOfUser: "/user/:userId",
		Create: "/create",
		Get: "/:storeId",
		Update: "/:storeId/update",
		Delete: "/:storeId/delete",
	},
	Products: {
		Base: "/products",
		GetAll: "/all",
		Get: "/:productId",
		Create: "/create",
		Update: "/:productId/update",
		Delete: "/:productId/delete",
	},
	Locations: {
		Base: "/locations",
		Create: "/create",
		Get: "/:locationId",
		Update: "/:locationId/update",
		Delete: "/:locationId/delete",
	},
	ServiceProviders: {
		Base: "/service-providers",
		Create: "/create",
		Get: "/:serviceProviderId",
		Update: "/:serviceProviderId/update",
		Delete: "/:serviceProviderId/delete",
	},
	Services: {
		Base: "/services",
		Create: "/create",
		Get: "/:serviceId",
		Update: "/:serviceId/update",
		Delete: "/:serviceId/delete",
	},
	Reviews: {
		Base: "/reviews",
		Create: "/create",
		Get: "/:reviewId",
		GetAll: "/all",
		Update: "/:reviewId/update",
		Delete: "/:reviewId/delete",
	},
	Appointments: {
		Base: "/appointments",
		GetAll: "/all",
		Create: "/create",
		Get: "/:appointmentId",
		Update: "/:appointmentId/update",
		Delete: "/:appointmentId/delete",
	},
	Vets: {
		Base: "/vets",
		Create: "/create",
		Get: "/:vetId",
		Update: "/:vetId/update",
		Delete: "/:vetId/delete",
	},
} as const;
