name: Auto Assign Issues

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: actions-ecosystem/action-issue-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          command: "/attempt"
