name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install Dependencies
              run: yarn install

            - name: Build All Packages
              run: yarn build

    test-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install Frontend Dependencies
              run: cd apps/native && yarn install

            - name: Run Frontend Tests
              run: cd apps/native && yarn test

    test-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install Backend Dependencies
              run: cd apps/api && yarn install

            - name: Run Backend Tests
              run: cd apps/api && yarn test
